// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	parking " hery-ciaputra/exercise-go-parking-lot/parking"
	mock "github.com/stretchr/testify/mock"
)

// LotAvailableNotifier is an autogenerated mock type for the LotAvailableNotifier type
type LotAvailableNotifier struct {
	mock.Mock
}

func (_m *LotAvailableNotifier) NotifyLotFull(l *parking.Lot) {
	//TODO implement me
	panic("implement me")
}

// NotifyLotAvailable provides a mock function with given fields: l
func (_m *LotAvailableNotifier) NotifyLotAvailable(l *parking.Lot) {
	_m.Called(l)
}

type mockConstructorTestingTNewLotAvailableNotifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewLotAvailableNotifier creates a new instance of LotAvailableNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLotAvailableNotifier(t mockConstructorTestingTNewLotAvailableNotifier) *LotAvailableNotifier {
	mock := &LotAvailableNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
